#!/usr/bin/env bash
set -euo pipefail

if test "${2:-}" != "break"; then
  say "session ended. Restarting apps."

  osascript -e 'tell application "Slack" to activate'
  osascript -e 'tell application "Mail" to activate'
  osascript -e 'tell application "Zulip" to activate'
  osascript -e 'tell application "Mail" to activate'
fi
