;;; init.el --- user init file -*- no-byte-compile: t -*-

;;; Commentary:
;;; Bootstrap everything.  As little as possible should live here.

;;; Code:

;; enable package.
(require 'package)
(setq package-enable-at-startup nil)
(package-initialize)

;; use-package dependencies
(require 'delight)

;;;; bootstrapping done! ;;;;

(defvar emacs-d
  (file-name-directory (file-chase-links load-file-name))
  "Our .emacs.d location.")

;; wrap use-package to load local packages
;; (defmacro local (from name &rest body)
;;   "Look in FROM for NAME, and send BODY to use-package."
;;   `(use-package ,name
;;      :straight nil
;;      :load-path ,from
;;      ,@body))

;; base packages. These set up the basic editor functionality I expect.
;; (local "setup" keys) ;; needs to be first to register :bind-leader and :bind-leader-local
;; (local "setup" vim) ;; needs to be second to register evil state maps

;; and the rest of the editor setup...
;; (local "setup" basics)
;; (local "setup" compilation)
;; (local "setup" completion)
;; (local "setup" diffing)
;; (local "setup" display)
;; (local "setup" fake-shell)
;; (local "setup" folding)
;; (local "setup" fuzzy-everything)
;; (local "setup" git)
;; (local "setup" icons)
;; (local "setup" jumping)
;; (local "setup" linting)
;; (local "setup" profiling)
;; (local "setup" project-nav)
;; (local "setup" projects)
;; (local "setup" services)
;; (local "setup" snippets)

;; language packages
;; (local "lang" coffeescript)
;; (local "lang" csv)
;; (local "lang" docker)
;; (local "lang" elixir)
;; (local "lang" elm)
;; (local "lang" graphviz)
;; (local "lang" haml)
;; (local "lang" haskell)
;; (local "lang" html)
;; (local "lang" idris)
;; (local "lang" javascript)
;; (local "lang" lang-json)
;; (local "lang" markdown)
;; (local "lang" nix)
;; (local "lang" ruby)
;; (local "lang" rust)
;; (local "lang" terraform)
;; (local "lang" toml)
;; (local "lang" yaml)


;; autogenerated stuff
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;;; init.el ends here
